### ISSUE TITLE
appscript copy error due to multiple gmail accounts

### ISSUE THREAD

**Issue by hellojas** [jcl5m1/VaccineRegistration#2]
potentially minor use case, but I wasn't able to do step #7

"Open this copy of the AppScript project for this repository. Click on the 'i' icon in the left panel to see the project overview. On the upper right, click on 'Make a copy' to create your own copy of this project. Then click on the title to rename the project to your own."

<img width="798" alt="Screen Shot 2021-04-23 at 6 01 22 PM" src="https://user-images.githubusercontent.com/1888003/115933917-eb358880-a45d-11eb-90c3-fe41f1092fb9.png">

looks like it happens if you have multiple gmail accounts signed in.

https://stackoverflow.com/questions/47045209/google-drive-page-not-found-sorry-unable-to-open-the-file-at-this-time

It worked once I logged out of all my accounts and only logged in with one gmail account.  Not sure if there is easy way to fix it except adding note to README.

**Comment by jcl5m1** [comment]
Thanks, I added this additional info to the readme.  I also updated the
public version of the App Script project (just required me to open and pull
the github repo again).   I also checked it was able to work with another
Google account (with only one account logged in).

Thanks.
